version: '3.8'

services:
  test-server:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./test-data:/usr/share/nginx/html:ro
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:80"]
      interval: 5s
      timeout: 3s
      retries: 3
      start_period: 10s